language: cpp

sudo: false

cache:
    apt: true
    directories:
        - $HOME/depend

matrix:
    include:
      # latest xcode for macOS 10.12
      - os: osx
        osx_image: xcode9.2
        compiler: clang
        env: PSCC=clang PSCXX=clang++

      - os: osx
        osx_image: xcode9.2
        compiler: clang
        env: PSCC=clang PSCXX=clang++
        language: generic
        python: 3.5

      - os: osx
        osx_image: xcode9.2
        compiler: clang
        env: PSCC=clang PSCXX=clang++
        language: generic
        python: 3.6

      - os: osx
        osx_image: xcode9.2
        compiler: clang
        env: PSCC=clang PSCXX=clang++
        language: generic
        python: 3.7

        
install:
    - |
        echo "*** Check versions ***"
        find / -name "python*" 2>/dev/null
        find / -name "pip*" 2>/dev/null
        python3 --version
        pip3 --version
        pip3 install --upgrade conan
        conan --version
        cmake --version
        rake --version

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd prosoft/core/tests
    - export CC=${PSCC} CXX=${PSCXX}

script:
  - |
    rake

after_success:
  - bash <(curl -s https://codecov.io/bash) || true
